### ISSUE TITLE
An upper bound should be specified for PortMidi

### ISSUE THREAD

**Issue by OlivierSohn** [tidalcycles/tidal-midi#57]
Hello,

[Portmidi](https://github.com/ninegua/PortMidi) adheres to [Haskell PVP](https://pvp.haskell.org/) for version bounds, hence in the .cabal file of this project, the bounds for `Portmidi` should be  : `>= 0.1.6 && < 0.2`

Else, I'm afraid that the next `Portmidi` version pushed to hackage will break the build of `tidal-midi` because [there are API breaking changes](https://github.com/ninegua/PortMidi/blob/master/CHANGELOG.md).

Thank you.

**Comment by hvr** [comment]
In order to address https://github.com/haskell-infra/hackage-trustees/issues/172 I had to perform   [Hackage metadata revisions](https://github.com/haskell-infra/hackage-trustees/blob/master/revisions-information.md) rectifying the inaccurate metadata for the following affected releases:

- https://hackage.haskell.org/package/tidal-midi-0.9.10/revisions/
- https://hackage.haskell.org/package/tidal-midi-0.9.9/revisions/
- https://hackage.haskell.org/package/tidal-midi-0.9.5.2/revisions/
- https://hackage.haskell.org/package/tidal-midi-0.9.4/revisions/
- https://hackage.haskell.org/package/tidal-midi-0.9.3/revisions/
